apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 모든 파드/서비스를 dev 네임스페이스로 배포
namespace: dev

# 운영용 앱 리소스와 dev 전용 통합 인그레스만 사용
resources:
  - ../frontend
  - ../backend
  - dev-ingress.yaml

