apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-broker
spec:
  image: rabbitmq:4.3.5
  replicas: 3
  service:
    type: ClusterIP
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                startupProbe:
                  failureThreshold: 60
                  httpGet:
                    path: /api/health/checks/local-alarms
                    port: 15671
                    scheme: HTTPS
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 5