apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 1. 공통 계정 및 인그레스
  - serviceAccount.yaml
  - backend-ingress.yaml

  # 2. 마이크로서비스 배포 파일들 (경로 지정)
  - auth/deployment.yaml
  - auth/pdb.yaml

  - user/deployment.yaml
  - user/service.yaml
  - user/pdb.yaml

  - order/deployment.yaml
  - order/pdb.yaml

  - payment/deployment.yaml
  - payment/pdb.yaml

  - product/deployment.yaml
  - product/pdb.yaml

  - oms/deployment.yaml
  - oms/pdb.yaml

  - wms/deployment.yaml
  - wms/pdb.yaml

  - scm/deployment.yaml
  - scm/pdb.yaml