apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shared-mysql-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: shared-mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: auth-service
        - podSelector:
            matchLabels:
              app: order-service
        - podSelector:
            matchLabels:
              app: payment-service
        - podSelector:
            matchLabels:
              app: user-service
      ports:
        - protocol: TCP
          port: 3306
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mysql-backup
              app.kubernetes.io/created-by: moco
        - podSelector:
            matchLabels:
              app: mysql-account-provisioner
      ports:
        - protocol: TCP
          port: 3306
      
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: moco-system
      ports:
        - protocol: TCP
          port: 33062
        - protocol: TCP
          port: 3306

    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: shared-mysql
      ports:
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 33060
        - protocol: TCP
          port: 33062
        - protocol: TCP
          port: 9081