apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-mysql-password-policy
data:
  plugin_load_add: "validate_password.so"
  default_password_lifetime: "90"
  validate_password.policy: "STRONG"
  validate_password.length: "12"
  password_history: "3"
  password_reuse_interval: "0"
