apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-mysql-password-policy
data:
  default_password_lifetime: "90"
  password_history: "3"
  password_reuse_interval: "0"

  plugin_load_add: "audit_log.so"
  audit_log: "FORCE_PLUS_PERMANENT"
  audit_log_file: "/var/log/mysql/audit.log"
  audit_log_format: "JSON"
  audit_log_policy: "ALL"
  audit_log_strategy: "ASYNCHRONOUS"
  audit_log_rotate_on_size: "104857600"
  audit_log_rotations: "5"
  loose_percona_telemetry_disable: "1"
