apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shared-mysql-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - REPLACE_WITH_ACTUAL_MOCO_SECRET_NAME
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shared-mysql-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shared-mysql-secret-reader
subjects: 
  - kind: User
    name: arn:aws:iam::596601390909:user/infra-jaehyeok
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: arn:aws:iam::596601390909:user/infra-jongwon
    apiGroup: rbac.authorization.k8s.io