# k8s/frontend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- pdb.yaml
- serviceAccount.yaml
  
images:
- name: 596601390909.dkr.ecr.ap-northeast-2.amazonaws.com/kurly-frontend
  newTag: 2345c29dec07b5b60208ea7116f41718d414a05e
