# k8s/frontend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- pdb.yaml
- serviceAccount.yaml
  
images:
- name: 596601390909.dkr.ecr.ap-northeast-2.amazonaws.com/kurly-frontend
  newTag: bde5612f1e97e4dfb2b8a45fec8024dcf50a70f5
