# k8s/frontend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- pdb.yaml
- serviceAccount.yaml
  
images:
- name: 596601390909.dkr.ecr.ap-northeast-2.amazonaws.com/kurly-frontend
  newTag: ac34b10bfa93e53b4bb57cb587527bd66f953fe9
