apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  name: shared-mysql
  labels:
    app.kubernetes.io/name: shared-mysql
    app.kubernetes.io/component: database
spec:
  replicas: 3
  podTemplate:
    spec:
      containers:
        - name: mysqld
          image: 596601390909.dkr.ecr.ap-northeast-2.amazonaws.com/kurly-moco-mysql:8.0.41-32.1
