apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  name: shared-mysql
  labels:
    app.kubernetes.io/name: shared-mysql
    app.kubernetes.io/component: database
spec:
  replicas: 3
  podTemplate:
    spec:
      containers:
        - name: mysqld
          image: ghcr.io/cybozu-go/moco/mysql:8.0.41
