apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.serverPort }}
      targetPort: {{ .Values.serverPort }}
