# user Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      nodeSelector:
        karpenter.sh/capacity-type: spot
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: user-service
      containers:
        - name: user-service
          image: 596601390909.dkr.ecr.ap-northeast-2.amazonaws.com/kurly-user:latest
          ports:
            - containerPort: 8080


