apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

configMapGenerator:
  - name: platform-overview-grafana-dashboard
    files:
      - platform-overview.json=dashboards/platform-overview.json
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: platform-observability
        app.kubernetes.io/component: dashboard
        grafana_dashboard: "1"