apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: moco
    repo: https://cybozu-go.github.io/moco/
    version: 0.20.0  # TODO: 최신 안정 버전 확인 후 반영
    releaseName: moco
    namespace: moco-system
    includeCRDs: true