{{- if eq .Values.serviceName "swagger-ui" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }}
          env:
            - name: URLS
              value: >-
                [
                  { "url": "https://dev.cloudyim.store/swagger-api/auth/v3/api-docs", "name": "1. Auth Service" },
                  { "url": "https://dev.cloudyim.store/swagger-api/users/v3/api-docs", "name": "2. User Service" },
                  { "url": "https://dev.cloudyim.store/swagger-api/orders/v3/api-docs", "name": "3. Order Service" },
                  { "url": "https://dev.cloudyim.store/swagger-api/payments/v3/api-docs", "name": "4. Payment Service" },
                  { "url": "https://dev.cloudyim.store/swagger-api/products/v3/api-docs", "name": "5. Product Service" },
                  { "url": "https://dev.cloudyim.store/swagger-api/wms/v3/api-docs", "name": "6. WMS Service" },
                  { "url": "https://dev.cloudyim.store/swagger-api/oms/v3/api-docs", "name": "7. OMS Service" },
                  { "url": "https://dev.cloudyim.store/swagger-api/scm/v3/api-docs", "name": "8. SCM Service" }
                ]
            - name: CONFIG_URL_FILTER_TYPE
              value: "combo"
            - name: BASE_URL
              value: "/docs"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
{{- end -}}