{{- if eq .Values.serviceName "swagger-ui" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }}
          env:
            - name: URLS
              value: >-
                [
                  { "url": "http://auth-service.dev.svc.cluster.local:8080/v3/api-docs", "name": "1. Auth Service" },
                  { "url": "http://order-service.dev.svc.cluster.local:8080/v3/api-docs", "name": "2. Order Service" },
                  { "url": "http://payment-service.dev.svc.cluster.local:8080/v3/api-docs", "name": "3. Payment Service" },
                  { "url": "http://product-service.dev.svc.cluster.local:8080/v3/api-docs", "name": "4. Product Service" },
                  { "url": "http://wms-service.dev.svc.cluster.local:8080/v3/api-docs", "name": "5. WMS Service" },
                  { "url": "http://oms-service.dev.svc.cluster.local:8080/v3/api-docs", "name": "6. OMS Service" },
                  { "url": "http://scm-service.dev.svc.cluster.local:8080/v3/api-docs", "name": "7. SCM Service" },
                  { "url": "http://user-service.dev.svc.cluster.local:8080/v3/api-docs", "name": "8. User Service" }
                ]
            - name: CONFIG_URL_FILTER_TYPE
              value: "combo"
            - name: BASE_URL
              value: "/docs"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace | default "dev" }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
{{- end -}}