# auth-service 전용 값 (공통은 values.yaml에서 물려받음)
serviceName: auth-service        # 이 서비스 이름
image:
  repository: kurly-auth              # ECR 창고 이름

database:
  type: mysql
  host: shared-mysql-primary.backend.svc.cluster.local   # TODO[1] 
  port: 3306
  name: auth_db                                          # TODO[2] 확인
  secretName: shared-mysql-accounts          # MySQL 공용 Secret
  username: auth_user                       # MySQL username key는 확인 필요
  passwordKey: auth_service_password   

serviceAccount:
  create: true
  name: auth-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::596601390909:role/auth-service-irsa 

userServiceBaseUrl: "http://user-service.backend.svc.cluster.local:8080"

# Auth Service 전용 필수 설정값
authConfig:
  jwtKmsKeyId: "alias/auth-jwt-sign-key"
  redirectUriKakao: "https://api.cloudyim.store/api/v1/auth/oauth/kakao/callback"
  redirectUriNaver: "https://api.cloudyim.store/api/v1/auth/oauth/naver/callback"
  allowedRedirectUris: "https://cloudyim.store,https://api.cloudyim.store/api/v1/auth/oauth/kakao/callback,https://api.cloudyim.store/api/v1/auth/oauth/naver/callback"
  frontendRedirectUri: "https://cloudyim.store/oauth/callback"
  kakaoClientId: "dummy-kakao-client-id"
  naverClientId: "dummy-naver-client-id"