# oms-service 전용 값 (공통은 values.yaml에서 물려받음)
serviceName: oms-service
image:
  repository: kurly-oms
  
database:
  type: postgresql
  host: shared-pg-rw.backend.svc.cluster.local
  port: 5432
  name: oms_db
  secretName: shared-pg-oms-service-credentials
  username: oms_user
  passwordKey: password
