# scm-service 전용 값 (공통은 values.yaml에서 물려받음)
serviceName: scm-service        # 이 서비스 이름
image:
  repository: kurly-scm              # ECR 창고 이름


database:
  type: postgresql
  host: shared-pg-rw.backend.svc.cluster.local           # TODO[1]
  port: 5432
  name: scm_db                                       # ← 서비스마다 변경
  secretName: shared-pg-scm-service-credentials   # 서비스별 Secret
  username: scm_user                                # PostgreSQL은 username key 있음
  passwordKey: password