# swagger-ui 전용 값 
serviceName: swagger-ui
replicaCount: 1
image:
  repository: swaggerapi/swagger-ui
  tag: latest

# 포트 설정 (Helm 차트 공통 템플릿에 맞춤)
service:
  port: 8080
  targetPort: 8080

# Swagger UI가 바라볼 API 문서 URL 환경변수 주입
env:
  - name: URLS
    value: >-
      [
        { "url": "https://dev.cloudyim.store/api/v1/auth/v3/api-docs", "name": "1. Auth Service" },
        { "url": "https://dev.cloudyim.store/api/v1/orders/v3/api-docs", "name": "2. Order Service" },
        { "url": "https://dev.cloudyim.store/api/v1/payments/v3/api-docs", "name": "3. Payment Service" },
        { "url": "https://dev.cloudyim.store/api/v1/products/v3/api-docs", "name": "4. Product Service" },
        { "url": "https://dev.cloudyim.store/api/v1/admin/wms/v3/api-docs", "name": "5. WMS Service" },
        { "url": "https://dev.cloudyim.store/api/v1/admin/oms/v3/api-docs", "name": "6. OMS Service" },
        { "url": "https://dev.cloudyim.store/api/v1/admin/scm/v3/api-docs", "name": "7. SCM Service" },
        { "url": "https://dev.cloudyim.store/api/v1/users/v3/api-docs", "name": "8. User Service" }
      ]
  - name: CONFIG_URL_FILTER_TYPE
    value: "combo"
  - name: BASE_URL
    value: "/docs"