# user-service 전용 값 (공통은 values.yaml에서 물려받음)
serviceName: user-service        # 이 서비스 이름
image:
  repository: kurly-user              # ECR 창고 이름

database:
  type: mysql
  host: shared-mysql-primary.backend.svc.cluster.local   # TODO[1]
  port: 3306
  name: user_db                                          # TODO[2] 확인
  secretName: shared-mysql-accounts          # MySQL 공용 Secret
  username: user_user                       # MySQL username key는확인 필요
  passwordKey: member_service_password