# wms-service 전용 값 (공통은 values.yaml에서 물려받음)
serviceName: wms-service        # 이 서비스 이름
image:
  repository: kurly-wms              # ECR 창고 이름


database:
  type: postgresql
  host: shared-pg-rw.backend.svc.cluster.local           # TODO[1]
  port: 5432
  name: wms_db                                       # ← 서비스마다 변경
  secretName: shared-pg-wms-service-credentials   # 서비스별 Secret
  username: wms_user                                # PostgreSQL은 username key 있음
  passwordKey: password

serviceAccount:
  create: true
  name: wms-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::596601390909:role/wms-service-irsa