apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: exporter
    release: prometheus
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - backend
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: exporter
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s