# apiVersion: v1
# kind: Secret
# metadata:
#   name: grafana-github-oauth
#   namespace: prometheus # Ingress와 동일하게 일치
# type: Opaque
# stringData:
#   GF_AUTH_GITHUB_CLIENT_SECRET: "d1c326d68f5bfdcb80dbda54dac5f0ae1370bae4"
#   GF_SECURITY_ADMIN_PASSWORD: "admin1234"