apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shared-pg-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - shared-pg-app
      - shared-pg-dba-admin-credentials 
      - shared-pg-product-service-credentials
      - shared-pg-wms-service-credentials
      - shared-pg-scm-service-credentials
      - shared-pg-oms-service-credentials
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shared-pg-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shared-pg-secret-reader
subjects: 
- kind: Group
  name: db-admin-readers
  apiGroup: rbac.authorization.k8s.io