apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: shared-pg-product-db
spec:
  cluster:
    name: shared-pg
  name: product_db
  owner: product_user
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: shared-pg-wms-db
spec:
  cluster:
    name: shared-pg
  name: wms_db
  owner: wms_user
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: shared-pg-scm-db
spec:
  cluster:
    name: shared-pg
  name: scm_db
  owner: scm_user
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: shared-pg-oms-db
spec:
  cluster:
    name: shared-pg
  name: oms_db
  owner: oms_user
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: shared-pg-ai-db
spec:
  cluster:
    name: shared-pg
  name: ai_db
  owner: ai_user