apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/5issue/total-k8s.git
    targetRevision: HEAD
    path: workloads/platform-observability/overlays/eks
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true