apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-provisioner
  labels:
    app.kubernetes.io/name: rabbitmq-provisioner
    app.kubernetes.io/component: credential-provisioning
automountServiceAccountToken: false
